// Generated by https://quicktype.io

import { Parada } from "./Parada";

export interface Boleto {
  id: number;
  fechaUso: Date;
  valido: boolean;
  tokenBoleto: string;
  paradaRuta: ParadaRuta;
  user: User;
}

export interface ParadaRuta {
  id: number;
  precio: string;
  ruta: Ruta;
  parada: Parada
}

export interface Ruta {
  id: number;
  distancia: number;
  anden: string;
  horaEntrada: string;
  horaSalida: string;
  to: Td;
  td: Td;
}

export interface Td {
  id: number;
  nombre: string;
  long: string;
  lat: string;
}

export interface User {
  id: string;
  name: string;
  email: string;
  emailVerified: boolean;
  image: string;
  createdAt: Date;
  updatedAt: Date;
}
