// Generated by https://quicktype.io

import { Parada } from "./Parada";

export interface Ruta {
  id: number;
  nombreTo: string;
  nombreTd: string;
  distancia: number;
  anden: string;
  horaEntrada: string;
  horaSalida: string;
  paradasRuta: ParadaRuta[]
}

export interface ParadaRuta {
  id: number
  precio: number
  parada: Parada
}
